// Definição centralizada do comportamento das tags
// block:      tags que devem ser formatadas como blocos (com quebra de linha e identação)
//             Exemplo de formatação:
//               <table>
//                 ...
//               </table>
// inline:     tags que podem aparecer dentro de outras sem quebra de linha obrigatória
//             Exemplo de formatação:
//               <p>
//                 Algum <span>texto</span> com <a href="#">link</a> e <strong>negrito</strong>.
//               </p>
// inlineText: tags que DEVEM ficar sempre na mesma linha do texto, ex: <strong>Texto</strong>
//             Exemplo de formatação:
//               <strong>Texto em negrito</strong>
//               <a href="#">Clique aqui</a>
export const TAG_BEHAVIOR: Record<string, { block: boolean, inline: boolean, inlineText: boolean }> = {
	// Confluence Storage Format
	'ac:layout': { block: true, inline: false, inlineText: false },
	'ac:layout-section': { block: true, inline: false, inlineText: false },
	'ac:layout-cell': { block: true, inline: false, inlineText: false },
	'ac:structured-macro': { block: true, inline: false, inlineText: false },
	'ac:rich-text-body': { block: true, inline: false, inlineText: false },
	'ac:parameter': { block: true, inline: false, inlineText: false },
	'ac:task-list': { block: true, inline: false, inlineText: false },
	'ac:task': { block: true, inline: false, inlineText: false },
	'ac:task-status': { block: false, inline: true, inlineText: true },
	'ac:task-body': { block: true, inline: false, inlineText: false },
	'ac:task-id': { block: false, inline: true, inlineText: true },
	'ac:task-uuid': { block: false, inline: true, inlineText: true },
	'ri:page': { block: true, inline: false, inlineText: false },
	'ri:attachment': { block: true, inline: false, inlineText: false },
	'ri:url': { block: true, inline: false, inlineText: false },
	'ri:shortcut': { block: true, inline: false, inlineText: false },
	'ri:user': { block: true, inline: false, inlineText: false },
	'ri:space': { block: true, inline: false, inlineText: false },
	'ri:content-entity': { block: true, inline: false, inlineText: false },
	'at:declarations': { block: true, inline: false, inlineText: false },
	'at:string': { block: true, inline: false, inlineText: false },
	'at:textarea': { block: true, inline: false, inlineText: false },
	'at:list': { block: true, inline: false, inlineText: false },
	'at:option': { block: true, inline: false, inlineText: false },
	'at:var': { block: true, inline: false, inlineText: false },
	// HTML-like
	'p': { block: false, inline: true, inlineText: true },
	'h1': { block: false, inline: true, inlineText: true },
	'h2': { block: false, inline: true, inlineText: true },
	'h3': { block: false, inline: true, inlineText: true },
	'h4': { block: false, inline: true, inlineText: true },
	'h5': { block: false, inline: true, inlineText: true },
	'h6': { block: false, inline: true, inlineText: true },
	'pre': { block: false, inline: true, inlineText: false },
	'blockquote': { block: false, inline: true, inlineText: false },
	'strong': { block: false, inline: true, inlineText: true },
	'em': { block: false, inline: true, inlineText: true },
	'u': { block: false, inline: true, inlineText: true },
	'sup': { block: false, inline: true, inlineText: true },
	'sub': { block: false, inline: true, inlineText: true },
	'code': { block: false, inline: true, inlineText: true },
	'a': { block: false, inline: true, inlineText: true },
	'span': { block: false, inline: true, inlineText: true },
	'small': { block: false, inline: true, inlineText: true },
	'big': { block: false, inline: true, inlineText: true },
	'table': { block: true, inline: false, inlineText: false },
	'tbody': { block: true, inline: false, inlineText: false },
	'tr': { block: false, inline: true, inlineText: true },
	'td': { block: false, inline: true, inlineText: true },
	'th': { block: false, inline: true, inlineText: true },
	'li': { block: false, inline: true, inlineText: true },

	
	// CSP
	'csp:parameters': { block: true, inline: false, inlineText: false },
	'csp:properties': { block: true, inline: false, inlineText: false },
	'csp:key': { block: false, inline: true, inlineText: true },
	'csp:value': { block: false, inline: true, inlineText: true },
	'csp:file_id': { block: false, inline: true, inlineText: true },
	'csp:labels_list': { block: false, inline: true, inlineText: true },
	'csp:parent_id': { block: false, inline: true, inlineText: true }
};

export const allowedTags: Record<string, string[]> = {
	// Tags de layout e macro do Confluence
	'ac:layout': ['type', 'version', 'ac:layout-section'],
	'ac:layout-section': ['type'],
	'ac:layout-cell': ['id', 'style'],
	'ac:structured-macro': ['ac:name'],
	'ac:parameter': ['ac:name'],
	'ac:rich-text-body': [],
	'ac:link': [],
	'ac:plain-text-link-body': [],
	'ac:link-body': [],
	'ac:anchor': ['ac:name'],
	'ac:task-list': [],
	'ac:task': [],
	'ac:task-status': [],
	'ac:task-body': [],
	'ac:placeholder': [],
	'ac:emoticon': ['ac:name'],
	// Tags de recursos (Resource Identifiers)
	'ri:page': ['ri:content-title', 'ri:space-key'],
	'ri:attachment': ['ri:filename'],
	'ri:url': ['ri:value'],
	'ri:shortcut': ['ri:key', 'ri:parameter'],
	'ri:user': ['ri:userkey'],
	'ri:space': ['ri:space-key'],
	'ri:content-entity': ['ri:content-id'],
	'ri:blog-post': ['ri:content-title', 'ri:posting-day'],
	// Tags de template (variables)
	'at:declarations': [],
	'at:string': ['at:name'],
	'at:textarea': ['at:name'],
	'at:list': ['at:name'],
	'at:option': ['at:value'],
	'at:var': ['at:name'],
	// Tags customizadas do plugin
	'csp:parameters': [],
	'csp:file_id': [],
	'csp:labels_list': [],
	'csp:parent_id': [],
	'csp:properties': [],
	'csp:key': [],
	'csp:value': [],
	// Tags HTML principais suportadas pelo formato storage
	'p': [],
	'h1': [],
	'h2': [],
	'h3': [],
	'h4': [],
	'h5': [],
	'h6': [],
	'strong': [],
	'em': [],
	'u': [],
	'sup': [],
	'sub': [],
	'code': [],
	'pre': [],
	'blockquote': [],
	'span': [],
	'small': [],
	'big': [],
	'a': ['href'],
	'ul': [],
	'ol': [],
	'li': [],
	'hr': [],
	'br': [],
	'table': [],
	'tbody': [],
	'thead': [],
	'tfoot': [],
	'tr': [],
	'td': [],
	'th': [],
	'img': ['src'],
	// Outras tags comuns
	'div': [],
	'center': [],
	'ac:image': [],
	'ac:status': [],
	// Adicione outras tags do storage format conforme necessário
};

export const allowedValues: Record<string, string[]> = {
	'ac:task-status': ['complete', 'incomplete'],
	'ac:layout@type': ['sectioned'],
	'ac:layout@version': ['1'],
	'ac:layout-section@type': ['single', 'double', 'triple', 'custom'],
	// Adicione outros valores permitidos conforme necessário
};

export const allowedHierarchy: Record<string, string[]> = {
	'ac:layout': [], // ac:layout pode ser root
	'ac:task': ['ac:task-list'],
	'ac:task-status': ['ac:task'],
	'ac:task-body': ['ac:task'],
	'ac:plain-text-link-body': ['ac:link'],
	'ri:page': ['ac:link', 'ri:attachment'],
	'ri:attachment': ['ac:link', 'ac:image'],
	'ri:url': ['ac:link', 'ac:image'],
	'ri:shortcut': ['ac:link'],
	'ri:user': ['ac:link'],
	'ri:space': ['ac:link'],
	'ri:content-entity': ['ac:link'],
	'at:string': ['at:declarations'],
	'at:textarea': ['at:declarations'],
	'at:list': ['at:declarations'],
	'at:option': ['at:list'],
	'at:var': ['p', 'td', 'th'],
	'ac:placeholder': ['ac:task-body', 'ul', 'li'],
	'csp:file_id': ['csp:parameters'],
	'csp:labels_list': ['csp:parameters'],
	'csp:parent_id': ['csp:parameters'],
	'csp:properties': ['csp:parameters'],
	'csp:key': ['csp:properties'],
	'csp:value': ['csp:properties'],
	'csp:parameters': [],
	'ac:layout-section': ['ac:layout'],
	'ac:layout-cell': ['ac:layout-section'],
	'p': ['ac:layout-cell'],
	'table': ['ac:layout-cell'],
	'ul': ['ac:layout-cell'],
	'ol': ['ac:layout-cell'],
	'blockquote': ['ac:layout-cell'],
	'h1': ['ac:layout-cell'],
	'h2': ['ac:layout-cell'],
	'h3': ['ac:layout-cell'],
	'h4': ['ac:layout-cell'],
	'h5': ['ac:layout-cell'],
	'h6': ['ac:layout-cell'],
	'ac:structured-macro': ['ac:layout-cell'],
	'ac:image': ['ac:layout-cell'],
	'thead': ['table'],
	'tbody': ['table'],
	'tfoot': ['table'],
	'tr': ['tbody', 'thead', 'tfoot'],
	'td': ['tr'],
	'th': ['tr'],
}; 